# Site settings
title: paulk-async
email: ohahaha822@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


